### ISSUE TITLE
ESPHome setup?

### ISSUE THREAD

**Issue by landonr** [Xinyuan-LilyGO/T-Display-S3#11]
I can't get display to work with ESPHome. Does anyone have any advice? here's my config

```
esphome:
  name: s3

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.4
    platform_version: 5.1.1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "123123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3 Fallback Hotspot"
    password: "123"

color:
  - id: gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "fonts/iosevka.ttf"
    id: iosvetta
    size: 24

display:
  - platform: st7789v
    model: Custom
    offset_height: 0
    offset_width: 0
    height: 170
    width: 320
    backlight_pin: GPIO38
    cs_pin: GPIO6
    dc_pin: GPIO7
    reset_pin: GPIO5
    lambda: |-
      it.print(50, 50, id(iosvetta), "Hello World!");
      it.rectangle(64, 64, 192, 112, id(gray));
```
